/**
 * Generates public/Gebrye-Amare-CV.pdf — a minimal, valid one-page resume
 * placeholder with a correct xref table so it opens cleanly in any reader.
 *
 * Run: node scripts/generate-cv.mjs
 * Replace the file with the real CV whenever it's ready (see lib/data.tsx).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const lines = [
  "Gebrye Amare",
  "Computer Engineer & Full-Stack Developer",
  "gebryeamare5@gmail.com | Ethiopia | github.com/gebryeamare",
  "",
  "EDUCATION",
  "BSc in Electrical and Computer Engineering - Computer Engineering",
  "Haramaya University | Graduated 2026 | CGPA 3.66/4.00",
  "Final project: Intelligent Patient Triage and Appointment Management",
  "System Using Machine Learning (Grade A+)",
  "",
  "EXPERIENCE",
  "Software / Full-Stack Development Intern",
  "Information Network Security Administration (INSA) | 09/2025 - 01/2026",
  "Cybersecurity risk analysis system using web technologies and ML.",
  "",
  "SKILLS",
  "Languages: Java, JavaScript, TypeScript, Python",
  "Frontend: HTML, CSS, Tailwind, React, Next.js, Flutter",
  "Backend: Node.js, Express.js, Django, Laravel, Spring Boot",
  "Databases: PostgreSQL, MySQL, MongoDB, Firebase",
  "Tools: Git, GitHub, Docker, Figma, Postman",
  "Specializations: Full-Stack, Mobile, Machine Learning, Cybersecurity",
  "",
  "NOTE: Placeholder resume - replace this file with the real CV.",
];

// Escape PDF string special characters.
const escapePdf = (s) => s.replace(/([\\()])/g, "\\$1");

const content = [
  "BT /F1 20 Tf 72 720 Td (" + escapePdf(lines[0]) + ") Tj ET",
  "BT /F1 11 Tf 72 700 Td (" + escapePdf(lines[1]) + ") Tj ET",
  "BT /F1 10 Tf 72 686 Td (" + escapePdf(lines[2]) + ") Tj ET",
  "BT /F1 13 Tf 72 648 Td (" + escapePdf(lines[4]) + ") Tj ET",
  "BT /F1 11 Tf 72 628 Td (" + escapePdf(lines[5]) + ") Tj ET",
  "BT /F1 10 Tf 72 612 Td (" + escapePdf(lines[6]) + ") Tj ET",
  "BT /F1 10 Tf 72 598 Td (" + escapePdf(lines[7]) + ") Tj ET",
  "BT /F1 10 Tf 72 584 Td (" + escapePdf(lines[8]) + ") Tj ET",
  "BT /F1 13 Tf 72 546 Td (" + escapePdf(lines[10]) + ") Tj ET",
  "BT /F1 11 Tf 72 526 Td (" + escapePdf(lines[11]) + ") Tj ET",
  "BT /F1 10 Tf 72 510 Td (" + escapePdf(lines[12]) + ") Tj ET",
  "BT /F1 10 Tf 72 496 Td (" + escapePdf(lines[13]) + ") Tj ET",
  "BT /F1 13 Tf 72 458 Td (" + escapePdf(lines[15]) + ") Tj ET",
  "BT /F1 10 Tf 72 438 Td (" + escapePdf(lines[16]) + ") Tj ET",
  "BT /F1 10 Tf 72 424 Td (" + escapePdf(lines[17]) + ") Tj ET",
  "BT /F1 10 Tf 72 410 Td (" + escapePdf(lines[18]) + ") Tj ET",
  "BT /F1 10 Tf 72 396 Td (" + escapePdf(lines[19]) + ") Tj ET",
  "BT /F1 10 Tf 72 382 Td (" + escapePdf(lines[20]) + ") Tj ET",
  "BT /F1 10 Tf 72 368 Td (" + escapePdf(lines[21]) + ") Tj ET",
  "BT /F1 10 Tf 72 330 Td (" + escapePdf(lines[23]) + ") Tj ET",
].join("\n");

const stream = `BT /F2 8 Tf 72 120 Td (Portfolio placeholder - regenerated by scripts/generate-cv.mjs) Tj ET\n${content}\n`;

const objects = [
  null, // 0: unused
  "<< /Type /Catalog /Pages 2 0 R >>", // 1
  "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", // 2
  "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>", // 3
  `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`, // 4
  "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>", // 5
  "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", // 6
];

let pdf = "%PDF-1.4\n";
const offsets = new Array(objects.length).fill(0);
for (let i = 1; i < objects.length; i++) {
  offsets[i] = Buffer.byteLength(pdf, "latin1");
  pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
}

const xrefStart = Buffer.byteLength(pdf, "latin1");
pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
for (let i = 1; i < objects.length; i++) {
  pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
}
pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;

const outPath = join(root, "public", "Gebrye-Amare-CV.pdf");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, pdf, "latin1");
console.log(`Wrote ${outPath} (${Buffer.byteLength(pdf, "latin1")} bytes)`);
